name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-vps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
        env:
          VITE_TG_BOT_TOKEN: ${{ secrets.VITE_TG_BOT_TOKEN }}
          VITE_TG_CHAT_ID: ${{ secrets.VITE_TG_CHAT_ID }}
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 46.17.42.111
          username: admin
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: /home/admin/site
          strip_components: 0
          rm: true
      - name: Reload nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: 46.17.42.111
          username: admin
          key: ${{ secrets.VPS_SSH_KEY }}
          script: sudo nginx -t && sudo systemctl reload nginx
